

//                                                                                 RRRMMMMMRRRRMMMMMMMMMMMMMMMMMMMMMRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRR
//                                                                           +RRRRRRRRR$$$R$RRMRMMMMMMMMMMMMMMMMMMMMMRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRR
//  23-8-22                                                               ~MRRRRRMMMMMMR$$$RRRRMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR
//                                                                    ~~=MRRR$RRRMRRRRR+=RRMMMRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR
//                                                                  ?=RRRRRRRRMMRRRRRRMRRMMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRR
//                                                              :=RRMRRRRRRRRRMMMMMMMMMMMRRMMR$RRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
//                                                            =?RRMRMMMMMMRRR$RMMMMMMMMRMMRRRRRRR$$$RMMMMMMRMMMMMMMMMMMMMMMMMMMMMMMMRMMMMMMMMMMMMMMMMMMMMRRRMMMMMM
//                                                           +?RRRRRRMMMRRRRMMMMRRMMMMMMMMMMMMMMRRMMRRRM$RMMMMMRMMMMMMMMMMMMMMMMMMR$MMMMMMMMMMMMMMMMMMMRRRRRMMMMMM
//                                                         R?RRRRRRRRRR$RRRRRRRRRRRRRRRRMMRRRMMRRNRRRMRMMMMMMMMMRMMMMMMMMMMRRRRRMRRRMMMMMMMMMMMMMRRMMRRRRRRRRRMMMM
//                                                       =MRRRMRRMRRRRRRRRRRRRRRRRRRRM$$RRRRMRRRMMRMMRMMRMMMMMMMMMMMMMMRMMRRRR$NMR$MMMMMMMMMMMMM?~RRRRRRRRRRRRRRRR
//                                                      =R+RRRRRRRRMRRRRRRRRRRRRR$?===~~~=+R?MMRRMMRRRRMRRMRMMMMMMMMMMMMMMMRR$RMRRMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRR
//                                                     +?$RRRRRRRMMMMMMMRMRRR$$?==~~~~~~~~====+?RMMM$RMMRMRRMRMMMMMRMMMMMMMRRMMMMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRR
//                                                   =+?+MRRRRMMMMMMMMMMMMR$+==~~~~::~~~~~~===+++RMRRRRRRMRMMRRRMMMMRRRMMMMRRMMMMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRR
//                                                  ==+RRR?RRRRRMMMMMM$MMRR?=~~~~~:::::::~~~===+?RRRRRRRRMMMMMMMRRMRRMMMMMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRRR
//                                                 ===$??RRRRRRRMMMMMRNMR$?+=~~~~::::::::~~~~===+?RRR$RRMMRRRMMRRMMMMMMMMMMRMMMMMMMMMMMMMRRRRRRRRRR$MMRMM$RRRRRRRR
//                                                 ~=RRRRRRRMRRRMMMMMMMRR?+=~~~~:::::::::~~~~====+RRRRMRRRR$$RMMRRMMRMMMRMMRMMMMMMMMMMMMMMRRRRRRMMMM+=~=+R$RRRRRRR
//                                                 =$RRRMMMMMRRRMMMMMMMR??=~~=~~:::::::::::~~~===+RRR$MMRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRR$$M:.??~   :+RRRRRRRR
//                                                 =?+MMMMMMRRMMRRMMMM$R?+R$$RRR$~::::::::::~~~==+RRRRRMRRRRRRMMMMMMMMMMMMMMRMMMMMMMMMMMMMMRR$R?~.+?,    =?RRRRRRR
//                                                  ?MRMRRRMMMMMRRMMMM??M==~=~==RRRR::::::::~~~==+RRRRRMMRMMMMMMMMMMMMRMMMMRRMMMMMMMMMMMMMMRRRRRM+RR~   ,=?RRRRRRR
//                                                  R$RRMRMMMMMRRMMMMR++++?RRRR$MRM$R+~~~~~~~===++RRRRRRMMMMMMMMMMMMMMMMRRMMMMMMMMMMMMMMMMMMMRRRRRRM?=~~+M$RRRRRRR
//                                                  +RRRMMMMRMRRMMMMR?+++?MMMMMMMMRMR?~~~~===RRRRRRRRRR$RMMMMMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR$MRRMRRRRRRRRR
//                 MRRRR$$RRRRRRRR$$R?+==++          =RRRMMRMRRRMMMM$?===~+R?~RRMMRRR+~~~=+RRR$R$?++$MRRMMMMMRRRRMMMMRMMRRMMMMMMMMMMMMMMMMMMMRMMRRRRRRRRRRRRRRMMRR
//              $RRRRRRRRRRRRRRRRRRRRRRRRR$RR?MMR=+RRRRRRRRRR$MMRMMM$?+~~~~?RR~R+~~R+=::~+RRR=MMMNRRRRMR?MMMMMRRMMMMMMMMMRMMMMMMMMMMMMMMMMMMMMMMRRMRRRRRRRRRMMMMRR
//          :MRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$MRRRRRR?MRMRRMMMMRMM$++~~~~~~=+?R?+==~::~MR$+,MRM?MMRRRRMMMMMMRRRMMRMMMRRRMMMMMMMMMMMMMMMMMMMMMRRRMRRRRRRRRRMMMMMM
//         $RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$RRRRRRMMMMRRR$MMMR?+=~:::::~~~~~~~~~:=$MR+R?$=+RRRRMRRRRMRRRR$RMMMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRRRRRRMMMMMMM
//       RRRRRRRRRRRRRRMRRRRRRRRRRRRRRRRRRRRRRRRRRRRRMRRRMMMRMRMRMMMR?+=~:::::::::~~~~:~=$M+==+?R$RR?RMRRRRMR$RM$RRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRMRMMMMMMMMM
//     RRRRRRRRRRRRRMMMMMMMMRRRRRRRRRRRRRRRRRRRRRMMMMRMMRMMMMMMMMMMNRR?=~~::::::::~~~~~~+$R======+++?RRRRRMMMRRRRRMMMMMMMMMMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
//    RRRRRRRRRRMMMMMMMMMMMMMMRMMMMRRRRRRRRRRRRRRMMMMMMMR$$MMMMMMMMMRM?+=~:::::::~==~~~~+$$+=======+?$RRRMRRMMMRRMMMMMMMMMRRMMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
//  +RRRRRRMMMMMMMMMMMMMMMMMMRRRRRMMMMMMRRRRRRRRRRMMMMMMMRRRMMMMMMMMR$R?+=~~::::~===~:~=+$R?==~~~==+RRRRRRRRMMMMMRMMMMMMMMMMMRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
//:MRRRRRMMMMMMMMMMMMMMMMMMMMRRRRRRMMMMMMMMMMMMMMRRMMMMMMMMRRRMMMMMMM$MM?+=~~:~:~===~::=+RRR=~~~~=+?MRRRRRMRMRRRRMMMMMMMRMRMRMRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
//RRRRRMMMMMMMMMMMMMMMMMMMMMMRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMRRMRMMMMNR$MR?+=~~~~~~$$?+=?MRRR~=====+?$RRMR$MRMMRMRRRRMMMMRMRRRRMMMMMMMMMMMMMRRRMMMMMMMMMMMMMMMMMMMM
//RRRRMMMMMMMMMMMMMMMMMRRRRRRMRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMRRMRMMMMRR$MR?+==~~~====M$RRR?=======?MRRMRMRMMMMMMMMMMMMMMMMMMRRMMMMMMMMMMMMMRRRRRMMMMMMMMMMMMMMMMMM
//RRMMMMMMMMMMMMMMMRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRMRMMMMRR$RR?++======+===??+=====++RRRRMMMMRRMRMMMMMMRRRRMMRMMMMMMMMMMMMMMMMMRRRRRRMMMMMMMMMMMMMMMM
//RMMMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMRMRMMMRRR$RRRR??R$MM?=++???++++++R$RRMRRRRRRMRRRRRMRRMMMMMMMMMMMMMMMMMMMMMMMRRRRRRRRMMMMMMMMMMMMMM
//MMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMRRMMMMRRR$MMRRRRM?R$$M$$MR??++?RM$RRRMRRRMMMRRMMMMMMRMMMMRMMMMMMMMMMRMMMMMMRRRRRRRRMMMMMMMMMMMMMM
//MMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMR$MMMMRRRRM$$M???+MMRRRRR$????MRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMRRRMMMRRRRRRRRRRRMMMMMMMMMMMMM
//MMMMMMMMMMMRRRRRRRRRRRRRRRRR$RRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMR$MMMMMRRRR$$R$R+==~+?R$$RRRR$RRRMRRMRRRMMMMMMMMMMMMMMMMMMMMMMMMRRRRRRMMMMRRRRRRRRRMMMMMMMMMMMMM
//MMMMMMMMMMRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMRRMMMMMMRR$MMMMRR$MM$RRRRM$RRRMMMRRMMRRMMRRMRRRMMMMMMMRRRMRRRR$R?+~~~MRMMRRRRRRRRRRMMMMMMMMMMMM
//MMMMMMMMMRR$RRRRRRRRR$MRRM$$RRRRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMM$MMMRRRMMMMMRRMR?++==~==+?RMRRRMMMMMMMRMMRMRMMRMRMMMMRRMMRMMMRR$MR+=~:::,,RRMMMMRRRRRRMMMMMMMMMMMM
//MMMMMMMMMRR$$RRRRRR$$R+==+?R$RRRRRRRR$RRRRRRRRRMMMMMMMMMMMMMMMMMMMRRMMMMMMMRRMR??+====+R$RRRRRRMMMMMRRMMMRRRMMRMMMMMRMMRRRRRRRRM?+=~::,,,+RMRMMMMRMMMMMMMMMMMMMM
//MMMMMMMMMMRRRRRRRRR$R=:,  :=R$RRRRRRR$$$RRRRRRRMMMMMMMMMMMMMMMMMMMMRRRMMMMMMMR$MR?+++?MRRRRRRRRMMMRRRRRRRRRRMMMRMMRRRMMRRR$RRRMRR+=~:::,,,,?RRMRRRMMMMMMMMMMMMMM
//MMMMMMMMMMMMMRRRRRRM?~     ,+M$RRRRRR$M$$RRRRRRRMMMMMMMMMMMMMMMMMMMMRRMMMMMMRRRRRRRRRRRRRRR$$$RMMRMRRRMRRMRMMMMMRRRRRRRRRRRRRMMM?=~~:::,,,,,,RRMMMMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMRRRR$R~      ~?MRRRRRR$MM$$RRRRRRMMMMMMMMMMMMMMMMMMMMRRRMMMMRRRRRRRRRRRRR$MMRRMRRMRRRMRMMMMRRMMMRRRRMMMRRMR$R$MR?+=~~:::,,,,,,,,+RRMMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMRRRRRMR=:   ,~?M$RRRRR$M$R$RRRRRRRMMMMMMMMMMMMMMMMMMMMRRMMMMRRRRRRR$$MMMMR????RR$RRM$RRMRMMMMRMRRMMRRRRRRRRRR$$?+==~~::,,,,,,,,,,,?RMMMMMMMMMMMMM
//MMMMMMMMMMMMMMMMRRRRR$M?~,:~=?MMRRRRR$$RRRRRRRRRMMMMMMMMMMMMMMMMMMMMMRRMMMRRRRRRRRR$MR??++++?RM$RRRRRRRMMMMMMMMMMMRRRRRRRMRM$~~~=~~~::,,,,,,,,,,,,:~RRMMMMMMMMMM
//MMMMMMMMMMMMMMMMMRRRRRR$R?+?RM$RRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRR$MR?++++??RRMMRRRRRMMMRRMRRRRRRRRRMM$R,=:~~==++==~~::,,,,,,,,,,,,,,=MRRRMMMMM
//MMMMMMMMMMMMMMMMMMRRRRRRR$M$$RRRRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMRMMRMRRRRRMRRRRRRRRRRMM?+++?RRRRRRM$RRRRRR$RRRR$R?,:,,,,,:::::~~~=+R+=~::,,,,,,,,,,,,,,:::=?$$$$
//MMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRRRRRRRRMMMRRRRMMMMMMMMMMMMMMMMMRRRMRMRRRRRRRRRRRRRRRR$M??????RRRRMR$RR?$:MMMMRR,,,,.,,,,,,,,::~~~:=?$M+~::,,,,,,,,,,,,,,,,::~~~~
//MMMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRRMMMMMMMMRRRRMMMMMMMMMMMMMMMMRRRRRMRRRRRRRRRRRRRRRRRRMR???RRRRR$MM??R~~++RR=,,,,...,,,,,,,,,::::~~=M$$+~::,,,,,,,,,,,,,,,,,,:::
//MMMMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRMMMMMMRRMMMRMMMMMMMMMMMMMMMMRRRRRMRRRRRRRRRRRRRRRRRRMRRRRRRR?$???=:~~~=+:,,,,,,...,,,,,.,,,:::::==+$$M+~::,,,,,,,,,,,,,,,,,,,,
//MMMMMMMMMMMMRMMMMMMMMRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR$MM$RRRRRRRRRRRRRRRR$MMRRRR???+,,,::~=:,,,,,,,,..,,,,.,,,,,::::,:=+$$$R=~:,,,,,,,,,,,,,,,,,,,,
//MMMMMMMMMMMMMMMMMMMMMMRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR$MRRRRRRRRRRRRRRRRRR$MMRRRR~,,,,,,,,,,,,,,,,,,,.,,,,...,,,::::,,,~=+$$$?~::,,,,,,,,,,,,,,,,,,,
//MMMMMMMMMMMMMMMMMMMMMMMRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRR$M?RRRRRRRRRRRRRRRRR$$$M?~::,,,::::,,,,,,,,,,.,,,,,,..,,,::,,,,,,~=+$$$R=::,,,,,,,,,,,,,,,,,,,
//MMMMMMMMMMMMMMMMMMMMMMMMRRRRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR$M??RRRRRRRRRRRRRRRRRR~::,,:::,:::,,....,,,:,,,,.,,..,,::,,,,,,::~==$M$M+~:,,,,,,,,,,,,,,,,,,~
//MMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRRRRRRRRRRRMMMMMMMMMMMMMMMMMMMMMMRRRMMRRRRRRRRRRRRRRR+=~~~:::~:::,,,,,,,,,,,,,,,,,:,.,,,,,:,,,,,,,,:~==~$$MM+~::,,,,,,,,,,,,,,,:+M
//MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRR$R?MR?RRR????RRR?+~~~=~~~::,::,,,,,,,,,,,,,,,::,,,,,,,,,,,,,,,,:~~=~MMMM+~::,,,,,,,,,,,,,,~+RM
//+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRR?RRRRR????????R?++~=~~::,,,,,,,,,,,,,,,,,,,:~,.,,,,,,,,,,,,,:::~=+MMMM?~::,,,,,,,,,,,,,~?RRM
//:?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRMRRRM$MMMMMM$$$$R===~~::,,,,,,,,,,,,,,,,,,,:::,,,,,,,,,,,,,,,:::~=MMMMM?=::,,,,,,,,,,,,~?MMMM
//::+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRRM$$$MMMMMM$$RRRR?+==:::,,,,,,,,,,,,,...,,:::::,....,,,,,,,,,,:::~=$MMMM?=:::,,,,,,,,,,:?$$$$M
//::::RN+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRRMR$MMMMM$$RRRRM??==~:,,,,,,,,,,,,,,,,,,,~~:,:.,..,,,,,,,,,,,,:::~=$MMMM?=~:,,,,,,,,,,:+$RRRRR
//::::,MNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRR$?$MMMM$$$RRRR$M?+~:,,,,,,,,,,,,,,,,,,,,,~:::.,...,,,,,,,,,,,,::~~~$MMMM?=~::,,,,,,,,,~R$$RRRR
//::::::RMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMR$?MMM$$$$RRRRR?~::,,,,,,,,,,,,,,,,,,,,,,,::,:,...,,,,,,,,,,,,,::~~~MMMMM?=~::,,,,,,,,:?RRRMM$$
//:::::::~MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRM$MMM$$$$$$M?=~::,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,,::~??MM?::~~=$$$$MR=~::,,,,,,,:=RRMMRRMM
//:~======+===+++RRRMRRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRMMMMMMMM$$R=~~::,,,,,,,,,,,,,,,,,,,,,::,,,,:....~=~~~========?~~~~$$$$MR=~:::,,,,,,~RRRMMMM$R
//++==+++++++=++++++?MMM$$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMR$MRMMM$$$$$$?=~~::,,,,,,,,.,,,,,,,,,,,,,,,,,,+,.~========~=~====+?+=M$$$$M+~:::,,,,,:=RRMMMM$RR
//?????++??+++++++?++??RMRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRMR$$$$$$$$$$?=~~::,,,,,,,,.,,,,,,,,,,,,,,,,,,::===================+RM$$$$M+~~::,,,,,~RRMMMMM$$$
//???????????+?++??????RMM$RMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRM$R$RR$$RRRM+=~::,,,,,,,,,,,,,,,,,,,,,,,,,:========================+?$$R$M+=~::,,,,:=M$$$$MMMMR
//RR???????????????RRR?RMMMM$MRMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMRRMRRRRRRRRRR$R+~:::,,,,,,,,,,,,,,,,,,,,,,,,,==++++++?==+==============+++$R$?=~:::,,,:?$RRRRRR$MR

